services:
  mysql:
    image: mysql:8.4.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: k4r
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    networks:
      - k4r_network
  redis:
    image: redis:7.4
    ports:
      - 6379:6379
    networks:
      - k4r_network

networks:
  k4r_network:
    driver: bridge