spring:
  application:
    name: k4r-server
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/k4r?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
  # Redis
  data:
    redis:
      host: localhost
      database: 0
      port: 6379

  docker:
    compose:
      enabled: true
      file: compose.yaml
  main:
    banner-mode: off
# Mybatis Flex
mybatis-flex:
  global-config:
    print-banner: false


